

//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SI642_BonoCorporativo.Models
{

    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;


    public partial class SI642Entities : DbContext
    {
        public SI642Entities()
            : base("name=SI642Entities")
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }


        public virtual DbSet<CoinType> CoinType { get; set; }

        public virtual DbSet<Method> Method { get; set; }

        public virtual DbSet<PaymentFrequency> PaymentFrequency { get; set; }

        public virtual DbSet<RateType> RateType { get; set; }

        public virtual DbSet<Transaction> Transaction { get; set; }

        public virtual DbSet<User> User { get; set; }

    }

}