//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI642_BonoCorporativo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transaction
    {
        public int Id { get; set; }

        [Display(Name = "Valor Nominal", Prompt = "Ingresar Valor Nominal", Description = "Valor Nominal")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Valor Nominal")]
        [Range(0.0, float.MaxValue)]
        public decimal FaceValue { get; set; }

        [Display(Name = "Valor Comercial", Prompt = "Ingresar Valor Comercial", Description = "Valor Comercial")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Valor Comercial")]
        [Range(0.0, float.MaxValue)]
        public decimal CommercialValue { get; set; }
        [Display(Name = "Tipo de Moneda", Prompt = "Ingresar Tipo de Moneda", Description = "Tipo de Moneda")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Tipo de Moneda")]
        public int CoinType_Id { get; set; }
        [Display(Name = "Fecha de Emisión", Prompt = "Ingresar Fecha de Emisión", Description = "Fecha de Emisión")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Fecha de Emisión")]
        public System.DateTime DateIssue { get; set; }
        [Display(Name = "Nº de Años", Prompt = "Ingresar Nº de Años", Description = "Nº de Años")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Nº de Años")]
        [Range(0, 100)]
        public int Years { get; set; }
        [Display(Name = "Frecuencia de pago", Prompt = "Ingresar Frecuencia de pago", Description = "Frecuencia de pago")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Frecuencia de pago")]
        public int PaymentFrequency_Id { get; set; }
        [Display(Name = "Método", Prompt = "Ingresar Método", Description = "Método")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Método")]
        public int Method_Id { get; set; }
        [Display(Name = "Tipo de Tasa", Prompt = "Ingresar Tipo de Tasa", Description = "Tipo de Tasa")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Tipo de Tasa")]
        public int RateType_Id { get; set; }
        [Display(Name = "Tasa de Interés", Prompt = "Ingresar Tasa de Interés", Description = "Tasa de Interés")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Tasa de Interés")]
        [Range(0.0, float.MaxValue)]
        public decimal InterestRate { get; set; }
        [Required]
        [Display(Name = "TCEA Emisor")]
        public decimal TCEAIssuer { get; set; }
        [Required]
        [Display(Name = "TREA Bonista")]
        public decimal TREAInvestor { get; set; }
        [Required]
        public int User_Id { get; set; }

        [Display(Name = "Valor Prima", Prompt = "Ingresar Valor Prima", Description = "Valor Prima")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Valor Prima")]
        [Range(0.0, float.MaxValue)]
        public double prima { get; set; }

        [Display(Name = "Valor CAVALI", Prompt = "Ingresar Valor CAVALI", Description = "Valor CAVALI")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Valor CAVALI")]
        [Range(0.0, float.MaxValue)]
        public double cavali { get; set; }

        [Display(Name = "Valor Colocación", Prompt = "Ingresar Valor Colocación", Description = "Valor Colocación")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Valor Colocación")]
        [Range(0.0, float.MaxValue)]
        public double colocacion { get; set; }

        [Display(Name = "Valor Flotación", Prompt = "Ingresar Valor Flotación", Description = "Valor Flotación")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Valor Flotación")]
        [Range(0.0, float.MaxValue)]
        public double flotacion { get; set; }

        [Display(Name = "Valor Estructuración", Prompt = "Ingresar Valor Estructuración", Description = "Valor Estructuración")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Valor Estructuración")]
        [Range(0.0, float.MaxValue)]
        public double estructuracion { get; set; }

        [Display(Name = "Valor COK", Prompt = "Ingresar Valor COK", Description = "Valor COK")]
        [Required(ErrorMessage = "Error: Debe ingresar el campo Valor COK")]
        [Range(0.0, float.MaxValue)]
        public double cok { get; set; }
        public virtual CoinType CoinType { get; set; }
        public virtual Method Method { get; set; }
        public virtual PaymentFrequency PaymentFrequency { get; set; }
        public virtual RateType RateType { get; set; }
        public virtual User User { get; set; }
    }
}
